/*
 * (c) Copyright 2005-2014 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package com.keba.demo.web.selenium.page.role;

import com.keba.demo.web.selenium.support.Page;
import com.keba.demo.web.selenium.support.elements.Autocomplete;
import com.keba.demo.web.selenium.support.elements.CustomWebElement;
import com.keba.demo.web.selenium.support.elements.EntityAction;
import com.keba.demo.web.selenium.support.elements.Messages;
import com.keba.demo.web.selenium.support.elements.OrderBy;
import com.keba.demo.web.selenium.support.elements.SearchForm;
import com.keba.demo.web.selenium.support.elements.Table;

@Page
public class RoleSearch {
    public Table table;
    public EntityAction entity;
    public Messages messages;
    public RoleSearchOrders orders;
    public RoleSearchForm form;

    public static class RoleSearchOrders extends CustomWebElement {
        public OrderBy roleName = new OrderBy("role_roleName");
    }

    public static class RoleSearchForm extends SearchForm {
        public Autocomplete roleName = new Autocomplete("form:roleName");
        public Autocomplete roleNameTerm = new Autocomplete("form:roleNameTerm");
    }
}