/*
 * (c) Copyright 2005-2014 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/support/element/CustomWebElement.p.vm.java
 */
package com.keba.demo.web.selenium.support.elements;

import com.keba.demo.web.selenium.support.WebClient;

public abstract class CustomWebElement {
    protected WebClient webClient;
}