/*
 * (c) Copyright 2005-2014 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.keba.demo.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.keba.demo.domain.Account;
import com.keba.demo.domain.Account_;
import com.keba.demo.printer.AccountPrinter;
import com.keba.demo.repository.AccountRepository;
import com.keba.demo.repository.support.SearchParameters;
import com.keba.demo.web.domain.support.GenericController;
import com.keba.demo.web.permission.AccountPermission;

/**
 * Stateless controller for {@link Account} conversation start.
 */
@Named
@Singleton
public class AccountController extends GenericController<Account, String> {
    public static final String ACCOUNT_EDIT_URI = "/domain/accountEdit.faces";
    public static final String ACCOUNT_SELECT_URI = "/domain/accountSelect.faces";

    @Inject
    public AccountController(AccountRepository accountRepository, AccountPermission accountPermission, AccountPrinter accountPrinter) {
        super(accountRepository, accountPermission, accountPrinter, ACCOUNT_SELECT_URI, ACCOUNT_EDIT_URI);
    }

    @Override
    protected SearchParameters defaultOrder(SearchParameters searchParameters) {
        return searchParameters.asc(Account_.username);
    }
}