/*
 * (c) Copyright 2005-2014 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 */
package com.keba.demo.web.domain;

import javax.annotation.PostConstruct;
import javax.inject.Inject;
import javax.inject.Named;

import com.keba.demo.domain.Account;
import com.keba.demo.domain.Account_;
import com.keba.demo.domain.Address;
import com.keba.demo.domain.Book;
import com.keba.demo.domain.Document;
import com.keba.demo.domain.Role;
import com.keba.demo.repository.AccountRepository;
import com.keba.demo.web.domain.support.GenericEditForm;
import com.keba.demo.web.domain.support.GenericToManyAssociation;
import com.keba.demo.web.domain.support.GenericToOneAssociation;
import com.keba.demo.web.faces.ConversationContextScoped;
import com.keba.demo.web.util.TabBean;

/**
 * View Helper/Controller to edit {@link Account}.
 */
@Named
@ConversationContextScoped
public class AccountEditForm extends GenericEditForm<Account, String> {
    @Inject
    protected AccountController accountController;
    @Inject
    protected AddressController addressController;
    protected GenericToOneAssociation<Address, Integer> homeAddress;
    @Inject
    protected BookController bookController;
    protected GenericToManyAssociation<Book, Integer> coolBooks;
    @Inject
    protected DocumentController documentController;
    protected GenericToManyAssociation<Document, String> edocs;
    @Inject
    protected RoleController roleController;
    protected GenericToManyAssociation<Role, Integer> securityRoles;
    protected TabBean tabBean = new TabBean();

    @Inject
    public AccountEditForm(AccountRepository accountRepository, AccountGraphLoader accountGraphLoader) {
        super(accountRepository, accountGraphLoader);
    }

    /**
     * View helper to store the x-to-many associations tab's index. 
     */
    @Override
    public TabBean getTabBean() {
        return tabBean;
    }

    /**
     * The entity to edit/view.
     */
    public Account getAccount() {
        return getEntity();
    }

    public String print() {
        return accountController.print(getAccount());
    }

    @PostConstruct
    void setupHomeAddressActions() {
        homeAddress = new GenericToOneAssociation<Address, Integer>(addressController, Account_.homeAddress) {
            @Override
            protected Address get() {
                return getAccount().getHomeAddress();
            }

            @Override
            protected void set(Address address) {
                getAccount().setHomeAddress(address);
            }
        };
    }

    public GenericToOneAssociation<Address, Integer> getHomeAddress() {
        return homeAddress;
    }

    @PostConstruct
    void setupCoolBooksActions() {
        coolBooks = new GenericToManyAssociation<Book, Integer>(getAccount().getCoolBooks(), bookController, Account_.coolBooks) {
            @Override
            protected void remove(Book book) {
                getAccount().removeBook(book);
            }

            @Override
            protected void add(Book book) {
                getAccount().addBook(book);
            }

            @Override
            protected void onCreate(Book book) {
                book.setOwner(getAccount()); // for display
            }
        };
    }

    public GenericToManyAssociation<Book, Integer> getCoolBooks() {
        return coolBooks;
    }

    @PostConstruct
    void setupEdocsActions() {
        edocs = new GenericToManyAssociation<Document, String>(getAccount().getEdocs(), documentController, Account_.edocs) {
            @Override
            protected void remove(Document document) {
                getAccount().removeEdoc(document);
            }

            @Override
            protected void add(Document document) {
                getAccount().addEdoc(document);
            }

            @Override
            protected void onCreate(Document edoc) {
                edoc.setOwner(getAccount()); // for display
            }
        };
    }

    public GenericToManyAssociation<Document, String> getEdocs() {
        return edocs;
    }

    @PostConstruct
    void setupSecurityRolesActions() {
        securityRoles = new GenericToManyAssociation<Role, Integer>(getAccount().getSecurityRoles(), roleController, Account_.securityRoles) {
            @Override
            protected void remove(Role role) {
                getAccount().removeSecurityRole(role);
            }

            @Override
            protected void add(Role role) {
                // add the object only to the securityRole side of the relation 
                getAccount().getSecurityRoles().add(role);
            }
        };
    }

    public GenericToManyAssociation<Role, Integer> getSecurityRoles() {
        return securityRoles;
    }
}
