/*
 * (c) Copyright 2005-2014 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package com.keba.demo.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.model.LazyDataModel;

import com.keba.demo.domain.AuditLog;
import com.keba.demo.repository.AuditLogRepository;
import com.keba.demo.web.domain.support.GenericLazyDataModel;
import com.keba.demo.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link AuditLog}
 */
@Named
@ConversationContextScoped
public class AuditLogLazyDataModel extends GenericLazyDataModel<AuditLog, Integer, AuditLogSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public AuditLogLazyDataModel(AuditLogRepository auditLogRepository, AuditLogController auditLogController, AuditLogSearchForm auditLogSearchForm,
            AuditLogExcelExporter auditLogExcelExporter) {
        super(auditLogRepository, auditLogController, auditLogSearchForm, auditLogExcelExporter);
    }
}