/*
 * (c) Copyright 2005-2014 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 */
package com.keba.demo.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.keba.demo.domain.AuditLog;
import com.keba.demo.repository.AuditLogRepository;
import com.keba.demo.web.domain.support.GenericEditForm;
import com.keba.demo.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link AuditLog}.
 */
@Named
@ConversationContextScoped
public class AuditLogEditForm extends GenericEditForm<AuditLog, Integer> {
    @Inject
    protected AuditLogController auditLogController;

    @Inject
    public AuditLogEditForm(AuditLogRepository auditLogRepository) {
        super(auditLogRepository);
    }

    /**
     * The entity to edit/view.
     */
    public AuditLog getAuditLog() {
        return getEntity();
    }

    public String print() {
        return auditLogController.print(getAuditLog());
    }
}
