/*
 * (c) Copyright 2005-2014 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 */
package com.keba.demo.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.model.LazyDataModel;

import com.keba.demo.domain.Document;
import com.keba.demo.repository.DocumentRepository;
import com.keba.demo.web.domain.support.GenericLazyDataModel;
import com.keba.demo.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link Document}
 */
@Named
@ConversationContextScoped
public class DocumentLazyDataModel extends GenericLazyDataModel<Document, String, DocumentSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public DocumentLazyDataModel(DocumentRepository documentRepository, DocumentController documentController, DocumentSearchForm documentSearchForm,
            DocumentExcelExporter documentExcelExporter) {
        super(documentRepository, documentController, documentSearchForm, documentExcelExporter);
    }
}